#!/usr/bin/env bash

function gitt() { if [ -z "$1" ]; then
		echo "no commit message supplied"
	else
		git add -v -A
		git commit -m $1
		git push
	fi
}

function extract {
    if [ -z "$1" ]; then
    # display usage if no parameters given
		echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
    else
		if [ -f $1 ] ; then
			NAME=${1%.*}
			mkdir $NAME && cd $NAME
			case $1 in
				*.tar.bz2)   tar xvjf ../$1    ;;
				*.tar.gz)    tar xvzf ../$1    ;;
				*.tar.xz)    tar xvJf ../$1    ;;
				*.lzma)      unlzma ../$1      ;;
				*.bz2)       bunzip2 ../$1     ;;
				*.rar)       unrar x -ad ../$1 ;;
				*.gz)        gunzip ../$1      ;;
				*.tar)       tar xvf ../$1     ;;
				*.tbz2)      tar xvjf ../$1    ;;
				*.tgz)       tar xvzf ../$1    ;;
				*.zip)       unzip ../$1       ;;
				*.Z)         uncompress ../$1  ;;
				*.7z)        7za e ../$1       ;;
				*.xz)        unxz ../$1        ;;
				*.exe)       cabextract ../$1  ;;
				*)           echo "extract: '$1' - unknown archive method" ;;
		esac
	else
		echo "$1 - file does not exist"
	fi
fi
}

function board {
    uname=pi
    ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $uname@$1
}

function sink {
    uname=pi
    ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $uname@$1 'sudo reboot'
}

function fixpitime {
    uname=pi
    ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $uname@$1 'date && sudo ntpdate tick.byu.edu && date'
}

function spyglass {
    origin=$(xdotool getwindowfocus)              # save current window focus
    google-chrome-stable "http://$1.byu.edu:8888/"      # open new chrome tab
    wid=$(xdotool search --desktop 0 --class "google-chrome" | tail -n1)
    xdotool windowactivate --sync $wid          # change focus to chrome
    xdotool windowactivate --sync $wid key F12  # open dev tools

    sleep .6
    xdotool windowactivate --sync $origin       # change focus back to origin
}
