#! /bin/sh

sxhkd &

bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor DVI-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus true

# randomize background every 10 minutes
watch -n600 feh --randomize --bg-fill ~/pictures/backgrounds/ &

# launch bars
$HOME/.config/polybar/launch.sh
